
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-4
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-CommonStatsFix","number":107,"title":"FIX: RecordCommonStatsJob Correctly Saves Stats in Repository","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/107"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Chat-Panel","number":100,"title":"FEATURE: ChatPanel and integration into the PlayPage","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/100"},{"author":{"id":"MDQ6VXNlcjU2MDYwNjY0","is_bot":false,"login":"publicqi","name":""},"headRefName":"Qi-FixPermission","number":99,"title":"fix: add role check for /api/usercommons/commons/all","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/99"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Chat-MessageCreate","number":98,"title":"FEATURE: ChatMessageCreate component","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/98"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Chat-MessageDisplay","number":97,"title":"FEATURE: Chat Message Display","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/97"},{"author":{"id":"MDQ6VXNlcjIwODAwNjI5","is_bot":false,"login":"MPriston","name":"Matt Priston"},"headRefName":"Matt-Demand-Frontend-New","number":94,"title":"FEATURE: Added new UI for Update health and Milk Cows Jobs","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/94"},{"author":{"id":"MDQ6VXNlcjY4NDMwOTQ5","is_bot":false,"login":"yuanchenmeng","name":"Yuanchen Meng"},"headRefName":"Yuanchen-Component-PagedTable","number":93,"title":"Paginated Profits Table on User Homepage","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/93"},{"author":{"id":"MDQ6VXNlcjU2MDYwNjY0","is_bot":false,"login":"publicqi","name":""},"headRefName":"Qi-DeleteUserBackend","number":85,"title":"Qi delete user backend","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/85"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"chat-backend-nth","number":76,"title":"Chat Message Backend API ","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/76"}]
