
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-4
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"Dav-buy-toast-msg","number":16,"title":"Buying Cows will No Longer Produce a Toast Message","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/16"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"DS-readme-and-template-update","number":15,"title":"docs:Links point to team instances","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/15"}]
