
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-4
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"Dav-degradation-rate","number":31,"title":"Degradation Rate Step is Mow 0.001","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/31"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-MutationWorkflows","number":30,"title":"FEATURE: Add incremental mutation testing for workflows 33 and 34","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/30"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"Dav-leaderboard-currency","number":17,"title":"Leaderboard now shows total wealth in USD currency","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/17"}]
