
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-4
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDYwNjY0","is_bot":false,"login":"publicqi","name":""},"headRefName":"Qi-FixPropMutation","number":110,"title":"Fix prop mutation","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/110"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"main","number":109,"title":"Add fixme to fix prop mutation","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/109"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Chat-Panel","number":100,"title":"FEATURE: ChatPanel and integration into the PlayPage","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/100"}]
