
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-4
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-WorkflowFix","number":38,"title":"Hotfix for mutation testing with multiple changed frontend files","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/38"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-TrackStats","number":37,"title":"Iain track stats","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/37"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"play-greetings","number":36,"title":"Random Greetings for Players on the Play Page","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/36"},{"author":{"id":"MDQ6VXNlcjIwODAwNjI5","is_bot":false,"login":"MPriston","name":"Matt Priston"},"headRefName":"Matt-Capacity-Backend","number":35,"title":"FEATURE: Added Capacity per User Feature","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/35"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-LeaderboardBack","number":32,"title":"FEATURE: Added back button to leaderboard page","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/32"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"Dav-leaderboard-currency","number":17,"title":"Leaderboard now shows total wealth in USD currency","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/pull/17"}]
